from django.shortcuts import render
from .forms import registration
from .models import Profile
from django.core.mail import send_mail

# Create your views here.

def home(request):
    form = registration()
    if(request.method =='POST'):
        form = registration(request.POST)
        if(form.is_valid()):
            form.save(commit=True)
            to_email1 = form.cleaned_data.get('email')
            fname_user = form.cleaned_data.get('fname')
            mail_message = "Hello Sir this mail is generated by django, Have a nice day "+"Username is :"+str(fname_user)+"\r"+"Email is :"+str(to_email1)
            send_mail('Greetings! Your registration is Successful',
            mail_message,
            'teamcodenova@gmail.com',
            [to_email1],
            fail_silently=False,)
            return render(request,'success.html')

        else:
            return render(request,'fail.html')

    return render(request,'index.html')


def search(request):

    if(request.method == 'POST'):
        a = request.POST.get('searchroll')
        b = Profile.objects.filter(roll = a)
        return render(request,'result.html',{'b':b,})
    return render(request,'search.html')
